dist: focal
language: python
os: linux

before_install:
  - cd $TRAVIS_BUILD_DIR/src
  - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
  - sudo apt-get install -y rsync minify nodejs
  - pip install -r requirements.txt
  - npm install

install:
  - ./update.sh

script:
  - rsync -aP --delete --exclude "js" --exclude "sass" ./static/ ./upload/
  - pybabel compile --directory=locale
  - $(npm bin)/gulp compile
  - ./generator.py --loglevel INFO --source $HOME/library-media-inventory/inventory.csv
  - $(npm bin)/gulp subresource-integrity

after_success:
  - find upload/ -type f -name "*.html" -exec minify {} --type html -o {} \;
  - find upload/ -type f -name "*.html" -exec echo "{}" \; -exec $(npm bin)/html-validator --file={} \;
  - $(npm bin)/http-server upload & $(npm bin)/wait-on http://localhost:8080
  - cd $TRAVIS_BUILD_DIR/tests && ../src/node_modules/.bin/cypress run --record --key $CYPRESS_RECORD_KEY

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - mkdocs build --clean
  - rsync -aP --delete ./docs_for_upload/ ./src/upload/docs/

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/src/upload
  strategy: git
  edge: true
  target_branch: gh-pages
  fqdn: bibliothek.metalab.ac.at
  committer_from_gh: true
  on:
    branch: main
