dist: focal
language: python
os: linux

install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports > /dev/null
  - sudo apt-get install -y golang-go rsync minify npm > /dev/null
  - export GOPATH=/tmp/go && go get github.com/Clever/csvlint/cmd/csvlint > /dev/null
  - pip install -r requirements.txt > /dev/null
  - npm install --global uglify-js uglifycss > /dev/null

before_script:
  - ./update.sh
  - /tmp/go/bin/csvlint /tmp/library-media-inventory/inventory.csv

script:
  - ./staticSiteGenerator.py
  - rsync -avP ./static/ ./upload/

before_deploy:
  - mkdir upload
  - echo "bibliothek.metalab.ac.at" > upload/CNAME
  - ./minify.sh # Minify html, css and js

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: upload
  strategy: git
  edge: true
  skip_cleanup: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: main
