dist: focal
language: python
os: linux

before_install:
  - cd $TRAVIS_BUILD_DIR/src
  - curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
  - sudo apt-get install -y rsync minify nodejs > /dev/null
  - pip install -r requirements.txt > /dev/null
  - npm install > /dev/null

install:
  - ./update.sh

script:
  - rsync -aq --delete --exclude "js" --exclude "sass" ./static/ ./upload/
  - $(npm bin)/gulp compile
  - ./staticSiteGenerator.py --loglevel INFO --source $HOME/library-media-inventory/inventory.csv --name "Metalab Library"
  - $(npm bin)/gulp subresource-integrity

after_success:
  - find upload/ -type f -name "*.html" -exec minify {} --type html -o {} \;
  - find upload/ -type f -name "*.html" -exec echo "{}" \; -exec $(npm bin)/html-validator --file={} \;
  - $(npm bin)/http-server upload & $(npm bin)/wait-on http://localhost:8080
  - cd $TRAVIS_BUILD_DIR/tests && ../src/node_modules/.bin/cypress run --record --key $CYPRESS_RECORD_KEY
  - ls -hall $TRAVIS_BUILD_DIR/src/upload

before_deploy:
  - echo "bibliothek.metalab.ac.at" > $TRAVIS_BUILD_DIR/src/upload/CNAME

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/src/upload
  strategy: git
  edge: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: main
