site_name: "Metalab Library OPAC"
repo_url: "https://github.com/Metalab/library-opac"
site_author: "Sebastian Elisa Pfeifer"
docs_dir: "docs"
site_dir: "docs/docs"
copyright: "MIT License 2020 Metalab"

markdown_extensions:
  - "pymdownx.highlight"
  - "pymdownx.superfences"
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "footnotes"

plugins:
  - "macros"

theme:
  name: "material"
  logo: "images/logo.png"
  favicon: "images/logo.png"
  font: false

nav:
  - Home: "index.md"
  - How to use it: "howtouse.md"
  - i18n: "locales.md"
  - About: "about.md"
  - 3rd Party Licenses: "3rdparty.md"
  - Issue Tracker: "https://github.com/Metalab/library-opac/issues"
